# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-2
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0
add_files Z:/HandyEQ-HW/HandyEQ/HandyEQ.runs/xadc_wiz_0_synth_1/xadc_wiz_0.dcp
set_property used_in_implementation false [get_files Z:/HandyEQ-HW/HandyEQ/HandyEQ.runs/xadc_wiz_0_synth_1/xadc_wiz_0.dcp]
set_property use_blackbox_stub false [get_files Z:/HandyEQ-HW/HandyEQ/HandyEQ.runs/xadc_wiz_0_synth_1/xadc_wiz_0.dcp]
read_verilog z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0_stub.v
read_vhdl -library gaisler {
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/leon3v3/leon3sh.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/leon3v3/leon3x.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/leon3v3/grfpwxsh.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/irqmp/irqmp.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/misc/misc.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/misc/rstgen.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/misc/gptimer.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/misc/ahbram.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/misc/ahbdpram.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/misc/ahbtrace_mmb.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/misc/ahbtrace_mb.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/misc/ahbtrace.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/misc/grgpio.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/misc/ahbstat.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/misc/logan.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/misc/apbps2.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/misc/charrom_package.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/misc/charrom.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/misc/apbvga.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/misc/svgactrl.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/misc/grsysmon.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/misc/gracectrl.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/misc/grgpreg.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/misc/ahb_mst_iface.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/misc/grgprbank.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/net/net.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/uart/uart.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/uart/libdcom.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/srmmu/libmmu.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/srmmu/mmutlbcam.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/srmmu/mmulrue.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/srmmu/mmulru.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/srmmu/mmutlb.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/srmmu/mmutw.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/srmmu/mmu.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/leon3/leon3.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/leon3/grfpushwx.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/leon3v3/tbufmem.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/leon3v3/dsu3x.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/leon3v3/dsu3.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/leon3v3/libfpu.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/leon3v3/libiu.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/leon3v3/libcache.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/leon3v3/libleon3.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/leon3v3/regfile_3p_l3.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/leon3v3/mmu_acache.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/leon3v3/mmu_icache.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/leon3v3/mmu_dcache.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/leon3v3/cachemem.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/leon3v3/mmu_cache.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/leon3v3/grfpwx.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/leon3v3/grlfpwx.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/leon3v3/iu3.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/leon3v3/proc3.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/leon3v3/leon3cg.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/leon3v3/leon3s.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/ddr/ddr1spax.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/ddr/ddr1spax_ddr.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/ddr/ahb2mig_series7_pkg.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/ddr/ahb2mig_series7.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/ddr/ahb2avl_async.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/ddr/ahb2avl_async_be.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/i2c/i2c.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/i2c/i2cmst.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/i2c/i2cmst_gen.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/i2c/i2cslv.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/i2c/i2c2ahbx.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/i2c/i2c2ahb.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/i2c/i2c2ahb_apb.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/i2c/i2c2ahb_gen.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/i2c/i2c2ahb_apb_gen.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/spi/spi.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/spi/spimctrl.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/spi/spictrlx.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/spi/spictrl.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/spi/spi2ahbx.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/spi/spi2ahb.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/spi/spi2ahb_apb.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/uart/apbuart.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/uart/dcom.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/uart/dcom_uart.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/uart/ahbuart.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/jtag/jtag.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/jtag/libjtagcom.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/jtag/jtagcom.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/jtag/ahbjtag.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/jtag/ahbjtag_bsd.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/jtag/bscanregs.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/jtag/bscanregsbd.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/jtag/jtagcom2.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/greth/ethernet_mac.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/greth/greth.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/greth/greth_mb.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/greth/greth_gbit.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/greth/greth_gbit_mb.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/greth/grethm.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/greth/rgmii.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/ddr/ddrpkg.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/ddr/ddrintpkg.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/ddr/ddrphy_wrap.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/ddr/ddrspa.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/ddr/ddr2spa.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/ddr/ddr2buf.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/ddr/ddr2spax.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/ddr/ddr2spax_ahb.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/ddr/ddr2spax_ddr.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/arith/arith.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/arith/mul32.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/arith/div32.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/memctrl/memctrl.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/memctrl/sdctrl.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/memctrl/sdctrl64.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/memctrl/sdmctrl.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/memctrl/srctrl.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/srmmu/mmuconfig.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/gaisler/srmmu/mmuiface.vhd
}
read_vhdl -library esa {
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/esa/memoryctrl/memoryctrl.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/esa/memoryctrl/mctrl.vhd
}
read_vhdl {
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/designs/leon3-digilent-nexys4/config.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/designs/leon3-digilent-nexys4/ahbrom.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/designs/leon3-digilent-nexys4/leon3mp.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/LEON3_softcore/TopXADC.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/LEON3_softcore/ADCapb.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/LEON3_softcore/PWM.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/LEON3_softcore/PWMapb.vhd
}
read_vhdl -library techmap {
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/unisim/tap_unisim.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/unisim/ddr_unisim.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/unisim/ddr_phy_unisim.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/unisim/sysmon_unisim.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/unisim/spictrl_unisim.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/allclkgen.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/allddr.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/allmem.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/allmul.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/allpads.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/alltap.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/clkgen.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/clkmux.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/clkand.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/ddr_ireg.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/ddr_oreg.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/ddrphy.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/syncram.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/syncram64.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/syncram_2p.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/syncram_dp.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/regfile_3p.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/tap.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/techbuf.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/nandtree.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/clkpad.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/clkpad_ds.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/inpad.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/gencomp/gencomp.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/gencomp/netcomp.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/inferred/memory_inferred.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/inferred/ddr_inferred.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/inferred/mul_inferred.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/inferred/ddr_phy_inferred.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/inferred/ddrphy_datapath.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/unisim/memory_virtex.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/unisim/memory_unisim.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/unisim/buffer_unisim.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/unisim/pads_unisim.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/unisim/clkgen_virtex.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/unisim/clkgen_unisim.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/syncrambw.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/syncram_2pbw.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/sdram_phy.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/syncreg.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/clkinv.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/inpad_ds.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/iodpad.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/iopad.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/iopad_ds.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/lvds_combo.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/odpad.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/outpad.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/outpad_ds.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/toutpad.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/skew_outpad.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/grlfpw_net.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/grfpw_net.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/leon4_net.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/mul_61x61.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/cpu_disas_net.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/ringosc.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/system_monitor.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/grgates.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/inpad_ddr.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/outpad_ddr.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/iopad_ddr.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/syncram128bw.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/syncram256bw.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/syncram128.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/syncram156bw.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/techmult.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/spictrl_net.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/maps/scanreg.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/techmap/unisim/mul_unisim.vhd
}
read_vhdl -library grlib {
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/grlib/stdlib/version.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/grlib/stdlib/config_types.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/grlib/stdlib/config.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/grlib/stdlib/stdlib.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/grlib/sparc/sparc.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/grlib/modgen/multlib.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/grlib/modgen/leaves.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/grlib/amba/amba.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/grlib/amba/devices.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/grlib/amba/defmst.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/grlib/amba/apbctrl.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/grlib/amba/ahbctrl.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/grlib/amba/dma2ahb_pkg.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/grlib/amba/dma2ahb.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/grlib/amba/ahbmst.vhd
}
read_vhdl -library eth {
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/eth/comp/ethcomp.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/eth/core/greth_pkg.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/eth/core/eth_rstgen.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/eth/core/eth_edcl_ahb_mst.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/eth/core/eth_ahb_mst.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/eth/core/greth_tx.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/eth/core/greth_rx.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/eth/core/grethc.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/eth/wrapper/greth_gen.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/eth/wrapper/greth_gbit_gen.vhd
}
read_vhdl -library opencores {
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/opencores/i2c/i2c_master_bit_ctrl.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/opencores/i2c/i2c_master_byte_ctrl.vhd
  Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/sources_1/imports/GRLIB/lib/opencores/i2c/i2coc.vhd
}
read_xdc Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/constrs_1/imports/LEON3_softcore/Nexys4_Master.xdc
set_property used_in_implementation false [get_files Z:/HandyEQ-HW/HandyEQ/HandyEQ.srcs/constrs_1/imports/LEON3_softcore/Nexys4_Master.xdc]

read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir Z:/HandyEQ-HW/HandyEQ/HandyEQ.data/wt [current_project]
set_property parent.project_dir Z:/HandyEQ-HW/HandyEQ [current_project]
synth_design -top leon3mp -part xc7a100tcsg324-2
write_checkpoint leon3mp.dcp
report_utilization -file leon3mp_utilization_synth.rpt -pb leon3mp_utilization_synth.pb
