# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Labtools 27-147} -limit 4294967295
create_project -in_memory -part xc7a100tcsg324-3
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0
read_vhdl {{Y:/DAT096-Embedded System Design/Workspace/FPGA/DAC_PWM/DAC_PWM.srcs/sources_1/new/pwm_top.vhd}}
read_xdc {{Y:/DAT096-Embedded System Design/Workspace/FPGA/DAC_PWM/DAC_PWM.srcs/constrs_1/new/pin_config.xdc}}
set_property used_in_implementation false [get_files {{Y:/DAT096-Embedded System Design/Workspace/FPGA/DAC_PWM/DAC_PWM.srcs/constrs_1/new/pin_config.xdc}}]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {Y:/DAT096-Embedded System Design/Workspace/FPGA/DAC_PWM/DAC_PWM.data/wt} [current_project]
set_property parent.project_dir {Y:/DAT096-Embedded System Design/Workspace/FPGA/DAC_PWM} [current_project]
synth_design -top PWM_TOP -part xc7a100tcsg324-3
write_checkpoint PWM_TOP.dcp
report_utilization -file PWM_TOP_utilization_synth.rpt -pb PWM_TOP_utilization_synth.pb
