# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
create_project -in_memory -part xc7a100tcsg324-3
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0

read_ip {{z:/.win/My Documents/DAT096_Embedded System Design Project/XADCv3/XADCwiz/XADCwiz.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xci}}
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files {{z:/.win/My Documents/DAT096_Embedded System Design Project/XADCv3/XADCwiz/XADCwiz.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xci}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {Z:/.win/My Documents/DAT096_Embedded System Design Project/XADCv3/XADCwiz/XADCwiz.data/wt} [current_project]
set_property parent.project_dir {Z:/.win/My Documents/DAT096_Embedded System Design Project/XADCv3/XADCwiz} [current_project]
synth_design -top xadc_wiz_0 -part xc7a100tcsg324-3 -mode out_of_context

rename_ref -prefix_all xadc_wiz_0
write_checkpoint -noxdef xadc_wiz_0.dcp
report_utilization -file xadc_wiz_0_utilization_synth.rpt -pb xadc_wiz_0_utilization_synth.pb
if { [catch {
  file copy -force {Z:/.win/My Documents/DAT096_Embedded System Design Project/XADCv3/XADCwiz/XADCwiz.runs/xadc_wiz_0_synth_1/xadc_wiz_0.dcp} {z:/.win/My Documents/DAT096_Embedded System Design Project/XADCv3/XADCwiz/XADCwiz.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.dcp}
  write_verilog -force -mode synth_stub {z:/.win/My Documents/DAT096_Embedded System Design Project/XADCv3/XADCwiz/XADCwiz.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0_stub.v}
  write_verilog -force -mode funcsim {z:/.win/My Documents/DAT096_Embedded System Design Project/XADCv3/XADCwiz/XADCwiz.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0_funcsim.v}
  write_vhdl -force -mode funcsim {z:/.win/My Documents/DAT096_Embedded System Design Project/XADCv3/XADCwiz/XADCwiz.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0_funcsim.vhdl}
} _RESULT ] } { 
  puts "Critical Warning: Unable to successfully create or copy supporting IP files."
}
