# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-3
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0
add_files {{Z:/.win/My Documents/DAT096_Embedded System Design Project/XADCv3/XADCwiz/XADCwiz.runs/xadc_wiz_0_synth_1/xadc_wiz_0.dcp}}
set_property used_in_implementation false [get_files {{Z:/.win/My Documents/DAT096_Embedded System Design Project/XADCv3/XADCwiz/XADCwiz.runs/xadc_wiz_0_synth_1/xadc_wiz_0.dcp}}]
set_property use_blackbox_stub false [get_files {{Z:/.win/My Documents/DAT096_Embedded System Design Project/XADCv3/XADCwiz/XADCwiz.runs/xadc_wiz_0_synth_1/xadc_wiz_0.dcp}}]
read_verilog {{z:/.win/My Documents/DAT096_Embedded System Design Project/XADCv3/XADCwiz/XADCwiz.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0_stub.v}}
read_vhdl {{Z:/.win/My Documents/DAT096_Embedded System Design Project/XADCv3/XADCwiz/XADCwiz.srcs/sources_1/new/TopXADC.vhd}}
read_xdc {{Z:/.win/My Documents/DAT096_Embedded System Design Project/XADCv3/XADCwiz/XADCwiz.srcs/constrs_1/imports/XADCv3/Nexys4_Master.xdc}}
set_property used_in_implementation false [get_files {{Z:/.win/My Documents/DAT096_Embedded System Design Project/XADCv3/XADCwiz/XADCwiz.srcs/constrs_1/imports/XADCv3/Nexys4_Master.xdc}}]

read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {Z:/.win/My Documents/DAT096_Embedded System Design Project/XADCv3/XADCwiz/XADCwiz.data/wt} [current_project]
set_property parent.project_dir {Z:/.win/My Documents/DAT096_Embedded System Design Project/XADCv3/XADCwiz} [current_project]
synth_design -top XADC_top -part xc7a100tcsg324-3
write_checkpoint XADC_top.dcp
report_utilization -file XADC_top_utilization_synth.rpt -pb XADC_top_utilization_synth.pb
